const express = require("express");
const pool = require("../db/pool");
const PDFDocument = require("pdfkit");
const { Resend } = require("resend");

const router = express.Router();
const resend = new Resend(process.env.RESEND_API_KEY);

// Helper function to create a PDF in memory and return it as a Buffer
function generatePDFBuffer(restaurantName, salesData, cancelData) {
  return new Promise((resolve, reject) => {
    try {
      // Use standard A4 page size
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      const primaryColor = "#111827"; // Dark Gray/Black
      const secondaryColor = "#4b5563"; // Medium Gray
      const greenColor = "#16a34a";
      const redColor = "#dc2626";

      // 1. HEADER SECTION
      // Draw a sleek background header
      doc.rect(0, 0, doc.page.width, 110).fill("#f8fafc");
      
      // Header Text
      doc.y = 40;
      doc.fillColor(primaryColor).fontSize(28).font("Helvetica-Bold").text(restaurantName, { align: "center" });

      const dateStr = new Date().toLocaleDateString("en-IN", {
        timeZone: "Asia/Kolkata",
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      });

      doc.moveDown(0.2);
      doc.fillColor(secondaryColor).fontSize(12).font("Helvetica").text(`End of Day (Z-Report)`, { align: "center" });
      doc.moveDown(0.1);
      doc.fillColor(secondaryColor).fontSize(10).font("Helvetica-Oblique").text(dateStr, { align: "center" });

      // Move Y below header
      doc.y = 140;

      // Helper function to draw a line
      const drawLine = () => {
        doc.y += 10;
        doc.strokeColor("#e2e8f0").lineWidth(1).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
        doc.y += 15;
      };

      // Helper function for receipt-style rows
      const printRow = (label, value, isBold = false, color = primaryColor) => {
        const startY = doc.y;
        doc.fillColor(primaryColor).fontSize(12).font(isBold ? "Helvetica-Bold" : "Helvetica");
        doc.text(label, 50, startY, { lineBreak: false });
        doc.fillColor(color).font(isBold ? "Helvetica-Bold" : "Helvetica").text(value, doc.page.width - 250, startY, { width: 200, align: "right", lineBreak: false });
        doc.y = startY + doc.currentLineHeight() + 8;
      };

      // 2. SALES SUMMARY SECTION
      doc.fillColor(primaryColor).fontSize(16).font("Helvetica-Bold").text("Sales Summary", 50, doc.y);
      drawLine();

      printRow("Total Completed Orders", `${salesData.total_orders}`);
      printRow("Gross Revenue", `Rs. ${Number(salesData.gross_revenue).toFixed(2)}`, true, greenColor);
      printRow("Total Discounts", `- Rs. ${Number(salesData.total_discount).toFixed(2)}`, false, redColor);
      printRow("Total Taxes (CGST+SGST)", `Rs. ${Number(salesData.total_tax).toFixed(2)}`, false, secondaryColor);
      
      doc.moveDown(1);

      // 3. PAYMENT BREAKDOWN SECTION
      doc.fillColor(primaryColor).fontSize(16).font("Helvetica-Bold").text("Payment Breakdown", 50, doc.y);
      drawLine();

      printRow("Cash Sales", `Rs. ${Number(salesData.cash_sales).toFixed(2)}`, false, greenColor);
      printRow("Online Sales", `Rs. ${Number(salesData.online_sales).toFixed(2)}`, false, greenColor);
      
      doc.moveDown(1);

      // 4. ORDER TYPE BREAKDOWN SECTION
      doc.fillColor(primaryColor).fontSize(16).font("Helvetica-Bold").text("Order Type Breakdown", 50, doc.y);
      drawLine();

      printRow("Dine-in Sales", `Rs. ${Number(salesData.dine_in_sales).toFixed(2)}`, false, greenColor);
      printRow("Takeaway Sales", `Rs. ${Number(salesData.takeaway_sales).toFixed(2)}`, false, greenColor);
      printRow("Delivery Sales", `Rs. ${Number(salesData.delivery_sales).toFixed(2)}`, false, greenColor);
      
      doc.moveDown(1);

      // 5. CANCELLATIONS SECTION
      doc.fillColor(primaryColor).fontSize(16).font("Helvetica-Bold").text("Cancellations", 50, doc.y);
      drawLine();

      printRow("Cancelled Orders", `${cancelData.cancelled_orders}`, false, redColor);
      printRow("Lost Value", `Rs. ${Number(cancelData.cancelled_value).toFixed(2)}`, true, redColor);

      doc.moveDown(1);

      // 6. FOOTER
      drawLine();

      const generatedAt = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
      doc
        .fontSize(9)
        .fillColor("#94a3b8")
        .font("Helvetica")
        .text(`Generated exactly at ${generatedAt} (IST)`, 50, doc.y, { align: "center" })
        .moveDown(0.2)
        .text("Automatically generated by Classic Chinese System.", { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// POST /api/reports/eod-report
router.post("/eod-report", async (req, res) => {
  try {
    // 1. Authentication Check
    const authHeader = req.headers["authorization"];
    const expectedSecret = process.env.CRON_SECRET_KEY;

    if (!expectedSecret || authHeader !== expectedSecret) {
      return res.status(401).json({ error: "Unauthorized. Invalid CRON_SECRET_KEY." });
    }

    if (!process.env.RESEND_API_KEY) {
      return res.status(500).json({ error: "RESEND_API_KEY is not configured." });
    }

    // 2. Fetch Active Businesses and Admin Emails
    const businessQuery = `
      SELECT b.id as business_id, bs.restaurant_name, a.email
      FROM businesses b
      JOIN business_settings bs ON bs.business_id = b.id
      JOIN admin_account a ON a.business_id = b.id
      WHERE b.is_active = true AND a.email IS NOT NULL AND a.email != ''
    `;
    const businessRes = await pool.query(businessQuery);
    const businesses = businessRes.rows;

    if (businesses.length === 0) {
      return res.status(200).json({ message: "No active businesses with configured admin emails found." });
    }

    // 3. Process each business
    const results = [];
    for (const b of businesses) {
      // Query Sales
      const salesQuery = `
        SELECT
          COUNT(*) as total_orders,
          COALESCE(SUM(total), 0) as gross_revenue,
          COALESCE(SUM(discount), 0) as total_discount,
          COALESCE(SUM(cgst + sgst), 0) as total_tax,
          COALESCE(SUM(
            CASE 
              WHEN payment_method IN ('online', 'upi', 'card') THEN total 
              WHEN payment_method = 'split' THEN split_upi 
              ELSE 0 
            END
          ), 0) as online_sales,
          COALESCE(SUM(
            CASE 
              WHEN payment_method = 'cash' THEN total 
              WHEN payment_method = 'split' THEN split_cash 
              ELSE 0 
            END
          ), 0) as cash_sales,
          COALESCE(SUM(CASE WHEN order_type = 'dine-in' THEN total ELSE 0 END), 0) as dine_in_sales,
          COALESCE(SUM(CASE WHEN order_type = 'takeaway' THEN total ELSE 0 END), 0) as takeaway_sales,
          COALESCE(SUM(CASE WHEN order_type = 'delivery' THEN total ELSE 0 END), 0) as delivery_sales
        FROM orders
        WHERE business_id = $1 
          AND status = 'completed'
          AND (created_at AT TIME ZONE 'Asia/Kolkata')::date = (NOW() AT TIME ZONE 'Asia/Kolkata')::date
      `;
      const salesRes = await pool.query(salesQuery, [b.business_id]);
      const salesData = salesRes.rows[0];

      // Query Cancellations
      const cancelQuery = `
        SELECT 
          COUNT(*) as cancelled_orders, 
          COALESCE(SUM(total), 0) as cancelled_value
        FROM orders
        WHERE business_id = $1 
          AND status = 'cancelled'
          AND (created_at AT TIME ZONE 'Asia/Kolkata')::date = (NOW() AT TIME ZONE 'Asia/Kolkata')::date
      `;
      const cancelRes = await pool.query(cancelQuery, [b.business_id]);
      const cancelData = cancelRes.rows[0];

      // Generate PDF
      const pdfBuffer = await generatePDFBuffer(b.restaurant_name, salesData, cancelData);
      
      const dateStr = new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" });
      const filename = `Z-Report-${b.restaurant_name.replace(/[^a-z0-9]/gi, '_')}-${dateStr.replaceAll('/', '-')}.pdf`;

      // Send Email
      try {
        await resend.emails.send({
          from: "Classic Chinese System <onboarding@resend.dev>", // Replace with verified domain if available
          to: b.email,
          subject: `Daily Z-Report: ${b.restaurant_name} (${dateStr})`,
          text: `Please find attached the automated End-of-Day Z-Report for ${dateStr}.`,
          attachments: [
            {
              filename: filename,
              content: pdfBuffer,
            },
          ],
        });
        results.push({ business: b.restaurant_name, email: b.email, status: "sent" });
      } catch (emailErr) {
        console.error(`Failed to send email to ${b.email} for ${b.restaurant_name}:`, emailErr);
        results.push({ business: b.restaurant_name, email: b.email, status: "failed", error: emailErr.message });
      }
    }

    res.status(200).json({ message: "EOD reports processed", results });
  } catch (error) {
    console.error("Error in EOD cron job:", error);
    res.status(500).json({ error: "Internal server error." });
  }
});

// POST /api/reports/weekly-menu-report
router.post("/weekly-menu-report", async (req, res) => {
  try {
    const authHeader = req.headers["authorization"];
    const expectedSecret = process.env.CRON_SECRET_KEY;

    if (!expectedSecret || authHeader !== expectedSecret) {
      return res.status(401).json({ error: "Unauthorized. Invalid CRON_SECRET_KEY." });
    }

    if (!process.env.RESEND_API_KEY) {
      return res.status(500).json({ error: "RESEND_API_KEY is not configured." });
    }

    const businessQuery = `
      SELECT b.id as business_id, bs.restaurant_name, a.email
      FROM businesses b
      JOIN business_settings bs ON bs.business_id = b.id
      JOIN admin_account a ON a.business_id = b.id
      WHERE b.is_active = true AND a.email IS NOT NULL AND a.email != ''
    `;
    const businessRes = await pool.query(businessQuery);
    const businesses = businessRes.rows;

    if (businesses.length === 0) {
      return res.status(200).json({ message: "No active businesses with configured admin emails found." });
    }

    const results = [];
    for (const b of businesses) {
      // Top 3 Winners
      const winnersQuery = `
        SELECT oi.name, SUM(oi.quantity)::int as total_sold
        FROM order_items oi
        JOIN orders o ON o.id = oi.order_id
        WHERE o.business_id = $1 AND o.status = 'completed'
          AND o.created_at >= NOW() - INTERVAL '7 days'
        GROUP BY oi.name
        ORDER BY total_sold DESC
        LIMIT 3
      `;
      const winnersRes = await pool.query(winnersQuery, [b.business_id]);
      const winners = winnersRes.rows;

      // Bottom 3 Losers
      const losersQuery = `
        SELECT oi.name, SUM(oi.quantity)::int as total_sold
        FROM order_items oi
        JOIN orders o ON o.id = oi.order_id
        WHERE o.business_id = $1 AND o.status = 'completed'
          AND o.created_at >= NOW() - INTERVAL '7 days'
        GROUP BY oi.name
        ORDER BY total_sold ASC
        LIMIT 3
      `;
      const losersRes = await pool.query(losersQuery, [b.business_id]);
      const losers = losersRes.rows;

      if (winners.length === 0 && losers.length === 0) {
        continue; // No sales this week
      }

      const winnersHtml = winners.map(w => `<li><strong>${w.name}</strong> - Sold ${w.total_sold} units 🏆</li>`).join('');
      const losersHtml = losers.map(l => `<li><strong>${l.name}</strong> - Sold ${l.total_sold} units 📉</li>`).join('');

      try {
        await resend.emails.send({
          from: "Classic Chinese System <onboarding@resend.dev>",
          to: b.email,
          subject: `Weekly Menu Performance: ${b.restaurant_name}`,
          html: `
            <h2>📊 Weekly Menu Winners & Losers</h2>
            <p>Here is your menu performance summary for the last 7 days.</p>
            
            <h3 style="color: #16a34a;">Top 3 Best Sellers</h3>
            <ul>${winnersHtml || "<li>No sales data available.</li>"}</ul>
            
            <h3 style="color: #dc2626;">Bottom 3 Worst Sellers</h3>
            <ul>${losersHtml || "<li>No sales data available.</li>"}</ul>
            
            <p><strong>Pro Tip:</strong> Consider running a promotion on your worst sellers or removing them from the menu to save inventory costs!</p>
          `,
        });
        results.push({ business: b.restaurant_name, email: b.email, status: "sent" });
      } catch (emailErr) {
        console.error(`Failed to send weekly report to ${b.email}:`, emailErr);
        results.push({ business: b.restaurant_name, email: b.email, status: "failed", error: emailErr.message });
      }
    }

    res.status(200).json({ message: "Weekly menu reports processed", results });
  } catch (error) {
    console.error("Error in weekly menu report cron job:", error);
    res.status(500).json({ error: "Internal server error." });
  }
});

module.exports = router;
